// <auto-generated />
using System;
using Innovision.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Innovision.Core.Persistence.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20250625235455_suffix_column")]
    partial class suffix_column
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.1.1-servicing")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Account", b =>
                {
                    b.Property<long>("AccountInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccountInfoId"));

                    b.Property<Guid>("AccountBonusId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCommission")
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)");

                    b.Property<Guid>("AccountCreditId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountObjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("AccountStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("BackIdPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Barangay")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BirthDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Commision")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("FmTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("ForVerification")
                        .HasColumnType("boolean");

                    b.Property<string>("FrontIdPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsDeclined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastSetPassword")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MartialStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NatureOfWork")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PaymentAccountId")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PermanentBarangay")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentMunicipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentRegion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentStreetOrPurok")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PresentBarangay")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PresentMunicipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PresentProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PresentRegion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PresentStreetOrPurok")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfilePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RefferralCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RefferralKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("SalaryRange")
                        .HasColumnType("integer");

                    b.Property<string>("SelfiePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SignaturePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SourceOfIncome")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("StreetOrPurok")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("AccountInfoId");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("AccountInfo", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.AccountHistory", b =>
                {
                    b.Property<long>("AccountHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccountHistoryId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountHistoryId");

                    b.HasIndex("AccountInfoId");

                    b.ToTable("AccountHistory", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.AccountSetting", b =>
                {
                    b.Property<long>("AccountSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccountSettingId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EmailNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("InAppNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("SmsNotification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("AccountSettingId");

                    b.HasIndex("AccountInfoId")
                        .IsUnique();

                    b.ToTable("AccountSetting", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.AddressCode", b =>
                {
                    b.Property<long>("AddressCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AddressCodeId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("BarangayCode")
                        .HasColumnType("text");

                    b.Property<string>("MunicipalityCode")
                        .HasColumnType("text");

                    b.Property<string>("PermBarangayCode")
                        .HasColumnType("text");

                    b.Property<string>("PermMunicipalityCode")
                        .HasColumnType("text");

                    b.Property<string>("PermProvinceCode")
                        .HasColumnType("text");

                    b.Property<string>("PermRegionCode")
                        .HasColumnType("text");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("text");

                    b.Property<string>("RegionCode")
                        .HasColumnType("text");

                    b.HasKey("AddressCodeId");

                    b.HasIndex("AccountInfoId");

                    b.ToTable("AddressCode", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.AdministrativeExclusion", b =>
                {
                    b.Property<int>("AdministrativeExclusionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdministrativeExclusionId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayDuration")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TimeDuration")
                        .HasColumnType("interval");

                    b.HasKey("AdministrativeExclusionId");

                    b.HasIndex("AccountId");

                    b.ToTable("AdministrativeExclusion", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Announcement", b =>
                {
                    b.Property<long>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AnnouncementId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBanner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SendTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("BranchId");

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLog", "Audit");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.BankReference", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("BankReference", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.BlockedUserHistory", b =>
                {
                    b.Property<long>("BlockedUserHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BlockedUserHistoryId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("BlockedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("BlockedUserHistoryId");

                    b.HasIndex("AccountInfoId");

                    b.ToTable("BlockedUserHistory", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Barangay")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("BranchBonusObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("BranchCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("BranchCreditObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DefaultAccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GameSiteAccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GameSiteManagerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentBarangay")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentMunicipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentRegion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentStreetOrPurok")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PresentBarangay")
                        .HasColumnType("text");

                    b.Property<string>("PresentMunicipality")
                        .HasColumnType("text");

                    b.Property<string>("PresentProvince")
                        .HasColumnType("text");

                    b.Property<string>("PresentRegion")
                        .HasColumnType("text");

                    b.Property<string>("PresentStreetOrPurok")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreetOrPurok")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("BranchId");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Deposit", b =>
                {
                    b.Property<long>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DepositId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepositStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepositId");

                    b.HasIndex("AccountInfoId");

                    b.HasIndex("DepositStatusId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Deposit", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.DepositStatus", b =>
                {
                    b.Property<int>("DepositStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepositStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepositStatusId");

                    b.ToTable("DepositStatus", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.FrequentlyAskQuestion", b =>
                {
                    b.Property<int>("FrequentlyAskQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FrequentlyAskQuestionId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("IsApplicationRelated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FrequentlyAskQuestionId");

                    b.HasIndex("GameId");

                    b.ToTable("FrequentlyAskQuestion", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GameObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("StandardMissedDraws")
                        .HasColumnType("integer");

                    b.HasKey("GameId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.GameDrawType", b =>
                {
                    b.Property<int>("GameDrawTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameDrawTypeId"));

                    b.Property<TimeSpan>("DrawSchedule")
                        .HasColumnType("interval");

                    b.Property<string>("DrawTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndCutOff")
                        .HasColumnType("interval");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartCutOff")
                        .HasColumnType("interval");

                    b.HasKey("GameDrawTypeId");

                    b.HasIndex("GameTypeId");

                    b.ToTable("GameDrawTypes");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.GameType", b =>
                {
                    b.Property<int>("GameTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameTypeId"));

                    b.Property<decimal>("CardPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("GameReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("GameTypeDesciption")
                        .HasColumnType("text");

                    b.Property<string>("GameTypeName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GameTypeId");

                    b.HasIndex("GameId");

                    b.ToTable("GameType", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.JackpotWinner", b =>
                {
                    b.Property<long>("JackpotWinnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JackpotWinnerId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApproverAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("BetValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyGameId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DrawDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DrawResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DrawResultId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("DrawTime")
                        .HasColumnType("interval");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<long>("GameScheduleId")
                        .HasColumnType("bigint");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("GameTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrossWinAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("JackpotWinnerStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NetWinAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("NumberOfWinners")
                        .HasColumnType("integer");

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrizePoolAmount")
                        .HasColumnType("numeric");

                    b.Property<long?>("ReleaserAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalBetAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JackpotWinnerId");

                    b.HasIndex("AccountInfoId");

                    b.HasIndex("ApproverAccountId");

                    b.HasIndex("GameId");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("JackpotWinnerStatusId");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.HasIndex("ReleaserAccountId");

                    b.ToTable("JackpotWinner", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.JackpotWinnerAttachment", b =>
                {
                    b.Property<long>("JackpotWinnerAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JackpotWinnerAttachmentId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("JackpotWinnerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JackpotWinnerAttachmentId");

                    b.HasIndex("JackpotWinnerId");

                    b.ToTable("JackpotWinnerAttachment", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.JackpotWinnerStatus", b =>
                {
                    b.Property<int>("JackpotWinnerStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JackpotWinnerStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JackpotWinnerStatusId");

                    b.ToTable("JackpotWinnerStatus", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.LiveStream", b =>
                {
                    b.Property<int>("LiveStreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LiveStreamId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LiveStreamId");

                    b.HasIndex("BranchId");

                    b.ToTable("LiveStream", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("RedirectUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NotificationId");

                    b.HasIndex("AccountInfoId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationType", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.OTP", b =>
                {
                    b.Property<long>("OtpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OtpID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerify")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OtpID");

                    b.ToTable("OTP", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<int>("CommissionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalNoOfItems")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OrderId");

                    b.HasIndex("AccountInfoId");

                    b.HasIndex("GameId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.OrderItem", b =>
                {
                    b.Property<long>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderItemId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AmountBet")
                        .HasColumnType("numeric");

                    b.Property<int>("BetItemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CompanyGameId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DrawDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DrawTime")
                        .HasColumnType("text");

                    b.Property<decimal>("ExcessAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasExcessAmount")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UsedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderItemId");

                    b.HasIndex("AccountInfoId");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.PlayerActivity", b =>
                {
                    b.Property<long>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ActivityId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExcludeDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Extended")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastDrawDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("LastDrawTime")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MissedDraws")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiredTopay")
                        .HasColumnType("boolean");

                    b.HasKey("ActivityId");

                    b.HasIndex("AccountInfoId");

                    b.ToTable("PlayerActivity", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.QuarantineKafka", b =>
                {
                    b.Property<long>("QuarantineKafkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("QuarantineKafkaId"));

                    b.Property<DateTimeOffset?>("AttemptedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KafkaTopic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KafkaValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("QuarantineKafkaId");

                    b.ToTable("QuarantineKafka", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.SelfExclusion", b =>
                {
                    b.Property<int>("SelfExclusionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SelfExclusionId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsIndefinite")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("SelfExclusionId");

                    b.HasIndex("AccountId");

                    b.ToTable("SelfExclusion", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.SelfLimit", b =>
                {
                    b.Property<int>("SelfLimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SelfLimitId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("AmountLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("SelfLimitId");

                    b.HasIndex("AccountId");

                    b.ToTable("SelfLimit", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.UserStatus", b =>
                {
                    b.Property<long>("UserStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserStatusId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("SubStatus")
                        .HasColumnType("integer");

                    b.HasKey("UserStatusId");

                    b.HasIndex("AccountInfoId");

                    b.ToTable("UserStatus", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTypeId"));

                    b.Property<int>("GroupType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleType")
                        .HasColumnType("integer");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserType", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.UserTypeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CashInLevel")
                        .HasColumnType("integer");

                    b.Property<string>("CashinDeposit")
                        .HasColumnType("text");

                    b.Property<bool>("IsMainUser")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestCredit")
                        .HasColumnType("text");

                    b.Property<int?>("RequestLevel")
                        .HasColumnType("integer");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("UserTypeConfig", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.WalletSetting", b =>
                {
                    b.Property<int>("WalletSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletSettingId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InitialMinimumDeposit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InitialMinimumWithdraw")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaximumDepositAtOnce")
                        .HasColumnType("numeric")
                        .HasColumnName("MaximumDepositAtOnce");

                    b.Property<decimal>("MaximumDepositPerDay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaximumWithdrawAtOnce")
                        .HasColumnType("numeric")
                        .HasColumnName("MaximumWithdrawAtOnce");

                    b.Property<decimal>("MaximumWithdrawPerDay")
                        .HasColumnType("numeric");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SubsequentMinimumDeposit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SubsequentMinimumWithdraw")
                        .HasColumnType("numeric");

                    b.Property<int>("TaxPercentage")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("numeric");

                    b.HasKey("WalletSettingId");

                    b.ToTable("WalletSetting", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Withdrawal", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionId"));

                    b.Property<long>("AccountInfoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("BankInfo")
                        .HasColumnType("text");

                    b.Property<int?>("BankReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageProof")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NotificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1);

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountInfoId");

                    b.HasIndex("BankReferenceId");

                    b.HasIndex("Status");

                    b.ToTable("Withdrawal", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.WithdrawalStatus", b =>
                {
                    b.Property<int>("WithdrawalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WithdrawalStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WithdrawalStatusId");

                    b.ToTable("WithdrawalStatus", (string)null);
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Account", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Branch", "Branch")
                        .WithMany("Account")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.UserType", "UserType")
                        .WithMany("Accounts")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.AccountHistory", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("AccountHistories")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.AccountSetting", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "AccountInfo")
                        .WithOne("AccountSetting")
                        .HasForeignKey("Innovision.Core.Domain.Entity.AccountSetting", "AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountInfo");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.AddressCode", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("AddressCodes")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.AdministrativeExclusion", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("AdministrativeExclusions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Announcement", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Branch", "Branch")
                        .WithMany("Announcements")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.BlockedUserHistory", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("BlockedUserHistories")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Deposit", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "AccountInfo")
                        .WithMany("Deposits")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.DepositStatus", "DepositStatus")
                        .WithMany("Deposits")
                        .HasForeignKey("DepositStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.PaymentMethod", "PaymentMethod")
                        .WithMany("Deposits")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountInfo");

                    b.Navigation("DepositStatus");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.FrequentlyAskQuestion", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Game", "Game")
                        .WithMany("FrequentlyAskQuestions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.GameDrawType", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.GameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.GameType", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Game", "Game")
                        .WithMany("GameTypes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.JackpotWinner", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("JackpotWinners")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.Account", "ApproverAccount")
                        .WithMany("ApprovedJackpotWinners")
                        .HasForeignKey("ApproverAccountId");

                    b.HasOne("Innovision.Core.Domain.Entity.Game", "Game")
                        .WithMany("JackpotWinners")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.GameType", "GameType")
                        .WithMany("JackpotWinners")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.JackpotWinnerStatus", "JackpotWinnerStatus")
                        .WithMany("JackpotWinners")
                        .HasForeignKey("JackpotWinnerStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.OrderItem", "OrderItem")
                        .WithOne("JackpotWinner")
                        .HasForeignKey("Innovision.Core.Domain.Entity.JackpotWinner", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.Account", "ReleaserAccount")
                        .WithMany("ReleasedJackpotWinners")
                        .HasForeignKey("ReleaserAccountId");

                    b.Navigation("Account");

                    b.Navigation("ApproverAccount");

                    b.Navigation("Game");

                    b.Navigation("GameType");

                    b.Navigation("JackpotWinnerStatus");

                    b.Navigation("OrderItem");

                    b.Navigation("ReleaserAccount");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.JackpotWinnerAttachment", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.JackpotWinner", "JackpotWinner")
                        .WithMany("JackpotWinnerAttachments")
                        .HasForeignKey("JackpotWinnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JackpotWinner");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.LiveStream", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Branch", "Branch")
                        .WithMany("LiveStreams")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Notification", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Order", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "AccountInfo")
                        .WithMany("Orders")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.Game", "Game")
                        .WithMany("Orders")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountInfo");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.OrderItem", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "AccountInfo")
                        .WithMany("OrderItems")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.GameType", "GameType")
                        .WithMany("OrderItems")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountInfo");

                    b.Navigation("GameType");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.PlayerActivity", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("PlayerActivities")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.SelfExclusion", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("SelfExclusions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.SelfLimit", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("SelfLimits")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.UserStatus", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "Account")
                        .WithMany("UserStatuses")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.UserTypeConfig", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.UserType", "UserType")
                        .WithMany("UserTypeAccessControls")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Withdrawal", b =>
                {
                    b.HasOne("Innovision.Core.Domain.Entity.Account", "AccountInfo")
                        .WithMany("Withdrawals")
                        .HasForeignKey("AccountInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovision.Core.Domain.Entity.BankReference", "BankReference")
                        .WithMany("Withdrawals")
                        .HasForeignKey("BankReferenceId");

                    b.HasOne("Innovision.Core.Domain.Entity.WithdrawalStatus", "WithdrawalStatus")
                        .WithMany("Withdrawals")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountInfo");

                    b.Navigation("BankReference");

                    b.Navigation("WithdrawalStatus");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Account", b =>
                {
                    b.Navigation("AccountHistories");

                    b.Navigation("AccountSetting")
                        .IsRequired();

                    b.Navigation("AddressCodes");

                    b.Navigation("AdministrativeExclusions");

                    b.Navigation("ApprovedJackpotWinners");

                    b.Navigation("BlockedUserHistories");

                    b.Navigation("Deposits");

                    b.Navigation("JackpotWinners");

                    b.Navigation("Notifications");

                    b.Navigation("OrderItems");

                    b.Navigation("Orders");

                    b.Navigation("PlayerActivities");

                    b.Navigation("ReleasedJackpotWinners");

                    b.Navigation("SelfExclusions");

                    b.Navigation("SelfLimits");

                    b.Navigation("UserStatuses");

                    b.Navigation("Withdrawals");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.BankReference", b =>
                {
                    b.Navigation("Withdrawals");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Branch", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Announcements");

                    b.Navigation("LiveStreams");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.DepositStatus", b =>
                {
                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Game", b =>
                {
                    b.Navigation("FrequentlyAskQuestions");

                    b.Navigation("GameTypes");

                    b.Navigation("JackpotWinners");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.GameType", b =>
                {
                    b.Navigation("JackpotWinners");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.JackpotWinner", b =>
                {
                    b.Navigation("JackpotWinnerAttachments");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.JackpotWinnerStatus", b =>
                {
                    b.Navigation("JackpotWinners");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.OrderItem", b =>
                {
                    b.Navigation("JackpotWinner")
                        .IsRequired();
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.PaymentMethod", b =>
                {
                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.UserType", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("UserTypeAccessControls");
                });

            modelBuilder.Entity("Innovision.Core.Domain.Entity.WithdrawalStatus", b =>
                {
                    b.Navigation("Withdrawals");
                });
#pragma warning restore 612, 618
        }
    }
}
